algoritmo "semnome"
// Função :
// Autor :
// Data : 21/08/2019
// Seção de Declarações 
var
n1,n2,n3,n4,media:real
inicio
// Seção de Comandos 
escreval("Media do aluno")
escreva("Digite a 1ª nota: ")
leia(n1)
escreva("Digite a 2ª nota: ")
leia(n2)
escreva("Digite a 3ª nota: ")
leia(n3)
escreva("Digite a 4ª nota: ")
leia(n4)
media<- (n1+n2+n3+n4)/4
escreval("A média do Aluno(a) é: ",media)
fimalgoritmo
